-- If you set this option the cursor will move to the Tagbar window when it is opened.
vim.g.tagbar_autofocus = 1

-- If this option is set the tags are sorted according to their name. If it is unset they are sorted according to their order in the source file. Note that in the second case Pseudo-tags are always sorted before normal tags of the same kind since they don't have a real position in the file.
vim.g.tagbar_sort = 0

-- If this option is set a case-insensitive comparison is used when the tags are sorted according to their name. If it is unset a case-sensitive comparison is used.
vim.g.tagbar_case_insensitive = 1

-- If you set this option the Tagbar window will automatically close when you jump to a tag.
vim.g.tagbar_autoclose = 0

vim.g.tagbar_updatetime = 10

-- default perl tagbar setting converted into lua, generated by type :TagbarGetTypeConfig perl, {short}:{long}[:{fold}[:{stl}]] in kinds, stl means statusline
vim.g.tagbar_type_perl = {
	kinds = {
		 'p:packages:0:0',
		 's:subroutines:0:1',
		 'c:constants:1:0',
		 'M:modules:1:0',
		 'f:formats:1:0',
		 'l:labels:1:0', -- label is very problematic, that is why I fold it and put it way down so that it wouln't affect subroutines
		 'd:subroutineDeclarations:0:0',
	},
}
